"""Cluster step of the SEO keyword pipeline.

Reads `data/keywords.csv` (the enriched keyword set from the discover/enrich
steps) and produces semantic clusters plus interpretable artifacts.

Pipeline:
    1. clean         drop dupes, coerce numeric columns, attach orig cluster names
    2. embed         sentence-transformers (multilingual MiniLM) -> embeddings.npy
    3. reduce        UMAP to 5D for clustering, 2D for visualisation
    4. sweep         HDBSCAN parameter grid (diagnostic, prints a table)
    5. cluster       final HDBSCAN with the chosen hyperparameters
    6. assign_noise  soft-assign hdb=-1 keywords to their nearest cluster centroid
                     (default-on; sets `noise_assigned=True` for downstream styling)
    7. label         attach human-readable cluster names (DE + EN)
    8. profile       per-cluster stats CSV (size, SV, KD, CPC, intent mix)

The hyperparameter choices (UMAP n_neighbors=15, HDBSCAN mcs=10 / ms=5 / eom)
are documented in docs/methodology.md, including the parameter sweep result
that justifies them. All values live in `src.config.Settings` so a
deployment can override them via `PIPELINE_CLUSTER_*` env vars without code
change. See docs/developer-guide.md for the full configuration model.

CLI:
    python -m src.cluster --step all
    python -m src.cluster --step embed,reduce,cluster,label
"""
from __future__ import annotations

import argparse
import json
import re
import warnings
from collections import Counter
from pathlib import Path

import numpy as np
import pandas as pd

from src.config import settings

import logging
from src.logging_config import setup_logging

logger = logging.getLogger(__name__)

warnings.filterwarnings("ignore")

# ---------------------------------------------------------------------------
# Paths and hyperparameters
# ---------------------------------------------------------------------------
#
# Hyperparameters live in src/config.py and are loaded from environment
# variables via Pydantic Settings. The aliases below keep the rest of the
# module readable. Any deployment can override via PIPELINE_CLUSTER_* env
# vars. See docs/decisions.md (ADR-12) for the precedence rules.

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
OUT = ROOT / "output"
CLUSTERING = OUT / "clustering"

EMBED_MODEL = settings.cluster_embedding_model

UMAP_N_NEIGHBORS = settings.cluster_umap_neighbors
UMAP_RANDOM_STATE = settings.cluster_umap_random_state
UMAP_METRIC = settings.cluster_umap_metric

HDBSCAN_MIN_CLUSTER_SIZE = settings.cluster_hdbscan_mcs
HDBSCAN_MIN_SAMPLES = settings.cluster_hdbscan_ms
HDBSCAN_METHOD = settings.cluster_hdbscan_method
HDBSCAN_METRIC = settings.cluster_hdbscan_metric

def _load_cluster_labels() -> tuple[dict[int, str], dict[int, str]]:
    """Load EN and DE cluster labels.

    Prefers `output/clustering/cluster_labels.json` (LLM-generated by
    `src.labels_llm`) over the curated `data/cluster_labels.yaml`. Falls
    back to YAML when the JSON is absent (e.g. fresh checkout, 4-step
    pipeline without API key). Keys are integers (cluster IDs, -1 noise).
    """
    import json as _json
    json_path = OUT / "clustering" / "cluster_labels.json"
    if json_path.exists():
        data = _json.loads(json_path.read_text(encoding="utf-8"))
        en = {int(k): v["en"] for k, v in data.items()}
        de = {int(k): v["de"] for k, v in data.items()}
        return en, de
    import yaml
    with open(ROOT / "data" / "cluster_labels.yaml") as f:
        data = yaml.safe_load(f)
    en = {int(k): v for k, v in data.get("en", {}).items()}
    de = {int(k): v for k, v in data.get("de", {}).items()}
    return en, de


CLUSTER_LABELS_EN, CLUSTER_LABELS_DE = _load_cluster_labels()

# Files written by each step. Keep a single source of truth so docs and code
# agree on what lives where.
F_CLEAN = CLUSTERING / "keywords_clean.csv"
F_EMB = CLUSTERING / "embeddings.npy"
F_UMAP_5D = CLUSTERING / "umap_5d.npy"
F_UMAP_2D = CLUSTERING / "umap_2d.npy"
F_LABELED = CLUSTERING / "keywords_labeled.csv"
F_PROFILES = CLUSTERING / "cluster_profiles.csv"
F_VIZ = CLUSTERING / "cluster_map.html"


# ---------------------------------------------------------------------------
# Step 1: clean
# ---------------------------------------------------------------------------


def step_clean(input_csv: Path = DATA / "keywords.csv",
               clusters_json: Path = OUT / "clusters.json") -> pd.DataFrame:
    """Load keywords, drop duplicates, coerce numerics, attach orig cluster names."""
    CLUSTERING.mkdir(parents=True, exist_ok=True)

    df = pd.read_csv(input_csv)
    logger.info(f"loaded {len(df)} rows, {df.shape[1]} cols")
    logger.info(f"dupes (keyword): {df.duplicated(subset=['keyword']).sum()}")

    for col in ("search_volume", "kd", "cpc_eur", "priority_score"):
        df[col] = pd.to_numeric(df[col], errors="coerce")

    df = df.drop_duplicates(subset=["keyword"]).reset_index(drop=True)
    df["keyword_clean"] = df["keyword"].str.lower().str.strip()

    if clusters_json.exists():
        names = {c["id"]: c["name"] for c in json.loads(clusters_json.read_text())["clusters"]}
        df["orig_cluster_name"] = df["category"].map(names)

    df.to_csv(F_CLEAN, index=False)
    logger.info(f"wrote {F_CLEAN.relative_to(ROOT)} ({len(df)} rows)")
    return df


# ---------------------------------------------------------------------------
# Step 2: embed
# ---------------------------------------------------------------------------


def step_embed() -> np.ndarray:
    """Compute multilingual sentence embeddings for each keyword.

    The L6 English-only MiniLM was rejected because zvoove keywords are German.
    L12 multilingual handles German morphology well enough for clustering at
    this scale, runs locally without a GPU, and weighs ~120 MB.
    """
    from sentence_transformers import SentenceTransformer

    df = pd.read_csv(F_CLEAN)
    logger.info(f"encoding {len(df)} keywords with {EMBED_MODEL}")
    model = SentenceTransformer(EMBED_MODEL)
    emb = model.encode(df["keyword"].tolist(), show_progress_bar=False,
                       normalize_embeddings=True)
    np.save(F_EMB, emb)
    logger.info(f"wrote {F_EMB.relative_to(ROOT)}, shape={emb.shape}")
    return emb


# ---------------------------------------------------------------------------
# Step 3: reduce (UMAP)
# ---------------------------------------------------------------------------


def step_reduce() -> tuple[np.ndarray, np.ndarray]:
    """Reduce embeddings to 5D for clustering and 2D for visualisation.

    Two reductions because the optima differ: density-based clustering wants
    a few more dimensions to keep local structure (5D), the map needs exactly 2.
    """
    import umap

    emb = np.load(F_EMB)
    logger.info(f"UMAP {emb.shape[1]}D -> 5D (clustering) + 2D (viz)")
    red5 = umap.UMAP(n_neighbors=UMAP_N_NEIGHBORS, n_components=5,
                     metric=UMAP_METRIC, min_dist=0.0,
                     random_state=UMAP_RANDOM_STATE).fit_transform(emb)
    red2 = umap.UMAP(n_neighbors=UMAP_N_NEIGHBORS, n_components=2,
                     metric=UMAP_METRIC, min_dist=0.1,
                     random_state=UMAP_RANDOM_STATE).fit_transform(emb)
    np.save(F_UMAP_5D, red5)
    np.save(F_UMAP_2D, red2)
    logger.info(f"wrote {F_UMAP_5D.relative_to(ROOT)}, {F_UMAP_2D.relative_to(ROOT)}")
    return red5, red2


# ---------------------------------------------------------------------------
# Step 4: sweep (diagnostic)
# ---------------------------------------------------------------------------


def step_sweep() -> pd.DataFrame:
    """HDBSCAN hyperparameter sweep. Prints a table, returns it as a DataFrame.

    Diagnostic only. The chosen final params (mcs=10, ms=5, eom) were picked
    from the plateau region of this sweep on the recovered manual run.
    See docs/methodology.md and docs/developer-guide.md.
    """
    import hdbscan
    from sklearn.metrics import silhouette_score

    red5 = np.load(F_UMAP_5D)
    rows = []
    logger.info(f"{'mcs':>4} {'ms':>4} {'method':>6} {'n_clu':>6} {'noise':>6} "
          f"{'noise%':>7} {'sil':>7}")
    for mcs in (5, 8, 10, 12, 15, 20):
        for ms in (1, 5):
            for method in ("eom", "leaf"):
                cl = hdbscan.HDBSCAN(min_cluster_size=mcs, min_samples=ms,
                                     cluster_selection_method=method,
                                     metric=HDBSCAN_METRIC)
                labs = cl.fit_predict(red5)
                n_clu = len(set(labs)) - (1 if -1 in labs else 0)
                noise = int((labs == -1).sum())
                mask = labs != -1
                sil = (silhouette_score(red5[mask], labs[mask])
                       if (mask.sum() > 10 and n_clu > 1) else float("nan"))
                rows.append({"mcs": mcs, "ms": ms, "method": method,
                             "n_clusters": n_clu, "noise": noise,
                             "noise_pct": noise / len(labs), "silhouette": sil})
                logger.info(f"{mcs:>4} {ms:>4} {method:>6} {n_clu:>6} {noise:>6} "
                      f"{noise / len(labs) * 100:>6.1f}% {sil:>7.3f}")
    return pd.DataFrame(rows)


# ---------------------------------------------------------------------------
# Step 5: cluster (final HDBSCAN + Ward comparison)
# ---------------------------------------------------------------------------


def step_cluster() -> pd.DataFrame:
    """Run the final HDBSCAN, plus a Ward hierarchical comparison for the writeup."""
    import hdbscan
    from scipy.cluster.hierarchy import fcluster, linkage
    from sklearn.metrics import (adjusted_rand_score,
                                 normalized_mutual_info_score, silhouette_score)

    red5 = np.load(F_UMAP_5D)
    df = pd.read_csv(F_CLEAN)

    logger.info(f"HDBSCAN mcs={HDBSCAN_MIN_CLUSTER_SIZE} "
          f"ms={HDBSCAN_MIN_SAMPLES} method={HDBSCAN_METHOD}")
    cl = hdbscan.HDBSCAN(min_cluster_size=HDBSCAN_MIN_CLUSTER_SIZE,
                         min_samples=HDBSCAN_MIN_SAMPLES,
                         cluster_selection_method=HDBSCAN_METHOD,
                         metric=HDBSCAN_METRIC)
    labs = cl.fit_predict(red5)
    df["hdb"] = labs
    n_clu = len(set(labs)) - (1 if -1 in labs else 0)
    noise = int((labs == -1).sum())
    logger.info(f"{n_clu} clusters, {noise} noise points "
          f"({noise / len(labs) * 100:.1f}%)")
    logger.info(f"sizes: {sorted(Counter(labs).items())}")

    logger.info("Ward hierarchical comparison (k=8,10,12)")
    Z = linkage(red5, method="ward")
    for k in (8, 10, 12):
        h = fcluster(Z, t=k, criterion="maxclust")
        sil = silhouette_score(red5, h)
        logger.info(f"          k={k}: silhouette={sil:.3f}")
    df["hier10"] = fcluster(Z, t=10, criterion="maxclust")
    df["hier12"] = fcluster(Z, t=12, criterion="maxclust")

    mask = df["hdb"] != -1
    orig = df["category"].astype("category").cat.codes
    logger.info("agreement metrics (excluding HDBSCAN noise)")
    logger.info(f"          HDB vs LLM original  ARI={adjusted_rand_score(orig[mask], df['hdb'][mask]):.3f}, "
          f"NMI={normalized_mutual_info_score(orig[mask], df['hdb'][mask]):.3f}")
    logger.info(f"          Hier(10) vs LLM      ARI={adjusted_rand_score(orig, df['hier10']):.3f}, "
          f"NMI={normalized_mutual_info_score(orig, df['hier10']):.3f}")
    logger.info(f"          HDB vs Hier(10)      ARI={adjusted_rand_score(df['hier10'][mask], df['hdb'][mask]):.3f}")

    df.to_csv(F_LABELED, index=False)
    logger.info(f"wrote {F_LABELED.relative_to(ROOT)}")
    return df


# ---------------------------------------------------------------------------
# Step 5b: assign_noise
# ---------------------------------------------------------------------------


def step_assign_noise() -> pd.DataFrame:
    """Soft-assign HDBSCAN noise points to their nearest cluster centroid.

    HDBSCAN marks sparse-region points with `hdb=-1`. For an SEO content
    plan every keyword needs a home, so we re-label noise points with the
    nearest cluster centroid in 5D UMAP space (Euclidean distance).

    The original noise status is preserved in the boolean column
    `noise_assigned` so the report and the cluster map can render border
    keywords with a different style if desired.
    """
    df = pd.read_csv(F_LABELED)
    red5 = np.load(F_UMAP_5D)

    df["noise_assigned"] = df["hdb"] == -1
    n_noise = int(df["noise_assigned"].sum())

    if n_noise == 0:
        logger.info("no noise points to assign")
        df.to_csv(F_LABELED, index=False)
        return df

    real_clusters = sorted(int(c) for c in df["hdb"].unique() if c != -1)
    if not real_clusters:
        logger.warning("no real clusters to assign noise to; skipping")
        df.to_csv(F_LABELED, index=False)
        return df

    centroids = np.array([
        red5[(df["hdb"].values == c)].mean(axis=0)
        for c in real_clusters
    ])
    noise_mask = df["noise_assigned"].values
    noise_pts = red5[noise_mask]

    dists = np.linalg.norm(noise_pts[:, None, :] - centroids[None, :, :], axis=2)
    nearest_idx = dists.argmin(axis=1)
    nearest_cluster = np.array([real_clusters[i] for i in nearest_idx])

    new_hdb = df["hdb"].values.copy()
    new_hdb[noise_mask] = nearest_cluster
    df["hdb"] = new_hdb.astype(int)
    df.to_csv(F_LABELED, index=False)

    counts = Counter(nearest_cluster.tolist())
    spread = ", ".join(f"c{cid}+{n}" for cid, n in sorted(counts.items()))
    logger.info(f"assigned {n_noise} noise points to nearest cluster ({spread})")
    return df


# ---------------------------------------------------------------------------
# Step 6: label
# ---------------------------------------------------------------------------


def step_label() -> pd.DataFrame:
    """Attach human-readable EN and DE labels by joining on cluster id.

    Curated labels in CLUSTER_LABELS_EN/DE only cover the 10-cluster
    baseline. If the active HDBSCAN config produces additional clusters
    (e.g. mcs=10 yields 13), fall back to a generic "Cluster N" label
    so downstream steps don't break with KeyError.
    """
    df = pd.read_csv(F_LABELED)

    def _label_en(cid: int) -> str:
        if cid == -1:
            return ""
        return CLUSTER_LABELS_EN.get(int(cid), f"Cluster {int(cid) + 1}")

    def _label_de(cid: int) -> str:
        if cid == -1:
            return ""
        return CLUSTER_LABELS_DE.get(int(cid), f"Cluster {int(cid) + 1}")

    df["hdb_label"] = df["hdb"].apply(_label_en)
    df["hdb_label_de"] = df["hdb"].apply(_label_de)
    df.to_csv(F_LABELED, index=False)
    curated = sum(1 for cid in df["hdb"].unique() if cid != -1 and int(cid) in CLUSTER_LABELS_EN)
    total = sum(1 for cid in df["hdb"].unique() if cid != -1)
    logger.info(f"attached labels to {len(df)} rows ({curated}/{total} clusters use curated labels)")
    return df


# ---------------------------------------------------------------------------
# Step 7: profile
# ---------------------------------------------------------------------------


def _top_terms(keywords: list[str], k: int = 6) -> list[str]:
    """Frequent stems across a cluster, useful for sanity-checking labels."""
    stop = {"software", "zeitarbeit", "zeitarbeitnehmer", "personaldienstleistung",
            "personaldienstleister", "und", "für", "der", "die", "das", "im", "in",
            "am", "mit", "von", "vs", "zu", "auf", "an", "bei", "nach", "aus"}
    words: list[str] = []
    for kw in keywords:
        for w in re.findall(r"[a-zäöüß]+", kw.lower()):
            if len(w) > 3 and w not in stop:
                words.append(w)
    return [t for t, _ in Counter(words).most_common(k)]


def step_profile() -> pd.DataFrame:
    """Per-cluster stats, useful for the writeup and for the brief step."""
    df = pd.read_csv(F_LABELED)
    rows = []
    for cid in sorted(df["hdb"].unique()):
        sub = df[df["hdb"] == cid].sort_values("search_volume", ascending=False)
        rows.append({
            "cluster_id": int(cid),
            "label_en": CLUSTER_LABELS_EN.get(cid, ""),
            "label_de": CLUSTER_LABELS_DE.get(cid, ""),
            "n_keywords": int(len(sub)),
            "total_sv": int(sub["search_volume"].sum()),
            "median_sv": int(sub["search_volume"].median()),
            "mean_kd": round(float(sub["kd"].mean()), 1),
            "median_kd": int(sub["kd"].median()),
            "mean_cpc": round(float(sub["cpc_eur"].mean()), 2),
            "mean_priority": round(float(sub["priority_score"].mean()), 1),
            "pct_commercial": round(float((sub["estimated_intent"] == "commercial").mean() * 100), 0),
            "top_5_kw_by_sv": "; ".join(sub.head(5)["keyword"].tolist()),
            "top_3_kw_by_priority": "; ".join(sub.nlargest(3, "priority_score")["keyword"].tolist()),
            "top_terms": "; ".join(_top_terms(sub["keyword"].tolist())),
        })
    prof = pd.DataFrame(rows)
    prof.to_csv(F_PROFILES, index=False)
    logger.info(f"wrote {F_PROFILES.relative_to(ROOT)} ({len(prof)} clusters)")
    return prof


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


STEPS = {
    "clean": step_clean,
    "embed": step_embed,
    "reduce": step_reduce,
    "sweep": step_sweep,
    "cluster": step_cluster,
    "assign_noise": step_assign_noise,
    "label": step_label,
    "profile": step_profile,
}

# Default --all sequence (sweep is diagnostic, not part of all)
DEFAULT_SEQUENCE = ("clean", "embed", "reduce", "cluster", "assign_noise", "label", "profile")


def main() -> None:
    setup_logging()
    p = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    p.add_argument("--step", default="all",
                   help="comma-separated steps from: " + ", ".join(STEPS) + " (or 'all')")
    args = p.parse_args()

    requested = (DEFAULT_SEQUENCE if args.step == "all"
                 else tuple(s.strip() for s in args.step.split(",")))
    unknown = [s for s in requested if s not in STEPS]
    if unknown:
        raise SystemExit(f"unknown step(s): {unknown}. valid: {list(STEPS)}")

    for name in requested:
        logger.info(f"\n=== {name} ===")
        STEPS[name]()


if __name__ == "__main__":
    main()
